[tool.poetry]
name = "formation-aws-data-eng"
version = "0.1.0"
description = ""
authors = ["Franck Cussac <fcussac.ext@galerieslafayette.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
